name: Publish binary
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true
      - run: go mod download
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          BINARY_NAME=pad

          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="pad.exe"
          fi

          go build -ldflags="-s -w" -o "$BINARY_NAME" main.go

          mkdir dist

          cp -r static "$BINARY_NAME" dist/

          ARCHIVE_NAME="pad-${{ matrix.goos }}-${{ matrix.goarch }}"

          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip -r "$ARCHIVE_NAME.zip" dist/
            echo "ASSET_PATH=$ARCHIVE_NAME.zip" >> $GITHUB_ENV
          else
            tar -czvf "$ARCHIVE_NAME.tar.gz" dist/
            echo "ASSET_PATH=$ARCHIVE_NAME.tar.gz" >> $GITHUB_ENV
          fi
      - uses: actions/upload-artifact@v6
        with:
          name: pad-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ env.ASSET_PATH }}
          retention-days: 5
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ASSET_PATH }}
          generate_release_notes: true
